# Tokyo Night — colori kitty (armonizzati con Starship)

# Colori principali
foreground #c0cdd9
background #1a2130

# Cursore
cursor #769ff0
cursor_text_color #1a2130

# Selezione
selection_background #394260
selection_foreground #e3e5e5

# Palette di colori ANSI
color0 #1a2130
color1 #e17287
color2 #8cbc6f
color3 #d0a863
color4 #769ff0
color5 #ac99e0
color6 #70bed9
color7 #a0a9cb
color8 #5a7390
color9 #e57b8e
color10 #9ac67d
color11 #d9b072
color12 #a3aed2
color13 #b8c0dc
color14 #7dcfff
color15 #e3e5e5

# Tab bar (coordinata con la status bar di tmux)
tab_bar_background #292e42
active_tab_background #6b94dd
active_tab_foreground #1a2130
inactive_tab_background #292e42
inactive_tab_foreground #c0cdd9
