# Catppuccin Mocha — tema tmux
set -g status-style bg="#313244",fg="#cdd6f4"
set -g status-left "#[fg=#11111b,bg=#89b4fa,bold] #S "
set -g status-right "#[fg=#11111b,bg=#89b4fa,bold] #H "

# Finestre
setw -g window-status-current-style fg="#11111b",bg="#89b4fa",bold
setw -g window-status-current-format " #I:#W "
setw -g window-status-style fg="#cdd6f4",bg="#313244"
setw -g window-status-format " #I:#W "

# Bordi pannelli
set -g pane-border-style fg="#45475a"
set -g pane-active-border-style fg="#89b4fa"

# Messaggi
set -g message-style bg="#89b4fa",fg="#11111b"
