# Prompt sequence setting
format = """
[░▒▓](#a3aed2)\
[  ](fg:#1a2440 bg:#a3aed2)\
[](fg:#a3aed2 bg:#6493ee)\
$directory\
[](fg:#6493ee bg:#566492)\
$git_branch\
$git_status\
[](fg:#566492 bg:#465373)\
$nodejs\
$rust\
$golang\
$php\
$python\
$rlang\
$haskell\
$lua\
$c\
$cpp\
$cmake\
[](fg:#465373 bg:#333c55)\
$time\
[ ](fg:#333c55)\
\n$character"""

# Second layer
[directory]
style = "fg:#e3e5e5 bg:#6493ee"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# third layer
[git_branch]
symbol = ""
style = "bg:#566492"
format = '[[ $symbol $branch ](fg:#96a2cc bg:#566492)]($style)'

[git_status]
style = "bg:#566492"
format = '[[($all_status$ahead_behind )](fg:#96a2cc bg:#566492)]($style)'

# Forth layer
[nodejs]
symbol = ""
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'

[rust]
symbol = ""
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'

[golang]
symbol = ""
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'

[php]
symbol = ""
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'

[lua]
symbol = "🌙"
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'
detect_extensions = ["lua"]

[python]
symbol = "🐍"
style = "bg:#465373"
format = '[[ $symbol ($version) ($virtualenv) ](fg:#8997c5 bg:#465373)]($style)'
detect_extensions = ["py"]
python_binary = ["python3"]

[haskell]
symbol = "" # icona haskell (nerd font)
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'
detect_extensions = ["hs", "lhs"]
detect_files = ["stack.yaml", "cabal.project"]
disabled = false

[c]
symbol = ""
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'
detect_extensions = ["c", "h"]

[cpp]
symbol = ""
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'
detect_extensions = ["cpp", "cc", "cxx", "hpp", "hh", "hxx"]

[rlang]
symbol = "📐"
style = "bg:#465373"
format = '[[ $symbol ($version) ](fg:#8997c5 bg:#465373)]($style)'
detect_extensions = ["R", "Rd", "Rmd", "Rproj", "Rsx"]

[cmake]
symbol = ""
style = "bg:#465373"
format = '[[ $symbol ](fg:#8997c5 bg:#465373)]($style)'
detect_files = ["CMakeLists.txt"]

# Fifth layer
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#333c55"
format = '[[  $time ](fg:#7b8bbf bg:#333c55)]($style)'
