# Tabby Matcha — tema tmux
set -g status-style bg="#33281f",fg="#f2e5d5"
set -g status-left "#[fg=#15100d,bg=#e8a15d,bold] #S "
set -g status-right "#[fg=#15100d,bg=#e8a15d,bold] #H "

# Finestre
setw -g window-status-current-style fg="#15100d",bg="#e8a15d",bold
setw -g window-status-current-format " #I:#W "
setw -g window-status-style fg="#f2e5d5",bg="#33281f"
setw -g window-status-format " #I:#W "

# Bordi pannelli
set -g pane-border-style fg="#57443f"
set -g pane-active-border-style fg="#e8a15d"

# Messaggi
set -g message-style bg="#e8a15d",fg="#15100d"
